name: Presubmit - Run Benchmarks

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
    branches:
      - main
concurrency:
  # Group all jobs for a given PR together, and cancel presubmit if a new commit is pushed.
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  test1:
    if: ${{ github.event.action == 'labeled' && github.event.label.name != 'bug' }}
    runs-on: ubuntu-latest
    steps:
    - name: "sup"
      run: |
        echo "HI"
